### ISSUE TITLE
Error: Cannot find module '../../../../src/core_plugins/elasticsearch/lib/kibana_index_mappings'

### ISSUE THREAD

**Issue by Shwethancs** [wtakase/kibana-own-home#105]
I am trying to migrate from 5.4.3 to 5.5 but  while start up of server am facing following issue:
 log   [09:48:44.574] [fatal] Error: Cannot find module '../../../../src/core_plugins/elasticsearch/lib/kibana_index_mappings'
   at Function.Module._resolveFilename (module.js:469:15)
   at Function.Module._load (module.js:417:25)
   at Module.require (module.js:497:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (D:/kibana5.5/kibana-5.5.0-windows-x86/plugins//server/proxy/create_kibana_index.js:5:1)
   at Module._compile (module.js:570:32)
   at loader (D:\kibana5.5\kibana-5.5.0-windows-x86\node_modules\babel-register\lib\node.js:144:5)
   at Object.require.extensions.(anonymous function) [as .js] (D:\kibana5.5\kibana-5.5.0-windows-x86\node_modules\babel-register\lib\node.js:154:7)
   at Module.load (module.js:487:32)
   at tryModuleLoad (module.js:446:12)
   at Function.Module._load (module.js:438:3)
   at Module.require (module.js:497:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (D:/kibana5.5/kibana-5.5.0-windows-x86/plugins//server/proxy/replace_kibana_index_in_path.js:3:1)
   at Module._compile (module.js:570:32)
   at loader (\node_modules\babel-register\lib\node.js:144:5)

**Comment by wtakase** [comment]
Maybe you use own_home v5.4.3. Could you try to use v5.5.0?

**Comment by Shwethancs** [comment]
Thank wtakase ..I am using v5.5.0 now..Am facing following issue.Please help:
Error: Uncaught TypeError: Cannot read property 'register' of undefined (http://localhost:5601/bundles/commons.bundle.js?v=15382:85)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15382:76:8884)

**Comment by wtakase** [comment]
I have no idea...bundles files are not updated correctly?

How did you update your own-home to v5.5.0.

For the updating, you need to remove the current plugin first, then install newer one.
https://www.elastic.co/guide/en/kibana/6.2/update-remove-plugin.html

For example,
```
$ ./bin/kibana-plugin remove own_home

$ ./bin/kibana-plugin install https://github.com/wtakase/kibana-own-home/releases/download/v5.5.0/own_home-5.5.0.zip
Attempting to transfer from https://github.com/wtakase/kibana-own-home/releases/download/v5.5.0/own_home-5.5.0.zip
Transferring 3561312 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

**Comment by Shwethancs** [comment]
thanks
