### ISSUE TITLE
path must be a string or Buffer

### ISSUE THREAD

**Issue by lyeesim988** [wtakase/kibana-own-home#109]
Hi I have installed kibana own_home and would like to integrate with search guard. I have this error that cause kibana couldnt be started:

```
Jul 18 08:58:56 ip-172-30-0-85 kibana:
 {"type":"error","@timestamp":"2018-07-18T08:58:56Z","tags":["fatal"],
 pid":12278,"level":"fatal","error":{"message":"path must be a string or Buffer","name":"TypeError",
 "stack":"TypeError: path must be a string or Buffer\n    at TypeError (native)\n  
 at Object.fs.openSync (fs.js:642:18)\n    at fs.readFileSync (fs.js:510:33)\n   
 at module.exports (/usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:33:14)\n
 at Plugin.init [as externalInit] (/usr/share/kibana/plugins/own_home/index.js:91:9)\n   
 at /usr/share/kibana/src/server/plugins/lib/plugin.js:86:26\n    at next (native)\n 
 at step (/usr/share/kibana/src/server/plugins/lib/plugin.js:10:191)\n    at /usr/share/kibana/src/server/plugins/lib/plugin.js:10:437\n
 at /usr/share/kibana/src/server/plugins/lib/plugin.js:10:99\n    at asyncRegister (/usr/share/kibana/src/server/plugins/lib/plugin.js:91:23)\n 
 at Object.register (/usr/share/kibana/src/server/plugins/lib/plugin.js:96:9)\n    at Object.target [as register]
 (/usr/share/kibana/node_modules/hapi/node_modules/joi/lib/object.js:77:34)\n    at each (/usr/share/kibana/node_modules/hapi/lib/plugin.js:317:14)\n  
 at iterate (/usr/share/kibana/node_modules/items/lib/index.js:36:13)\n    at Object.exports.serial (/usr/share/kibana/node_modules/items/lib/index.js:39:9)"},
 "message":"path must be a string or Buffer"}
```
**Running on AWS ec2:**

search guard plugin : 6.2.4
Kibana-search-guard : 6.2.4
Elasticsearch: 6.2.4 
Kibana : 6.2.4

I am using self-signed certificated in search-guard. This is my kibana.yml configuration for own_home part:

```
server.defaultRoute: /app/own_home
elasticsearch.url: "https://localhost:19200"
elasticsearch.requestHeadersWhitelist: ["cookie", "authorization"]
elasticsearch.ssl.verificationMode: certificate
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: "https://31.40.219.112:9200"
own_home.session.secretkey: $2y$12$b1BHg130RFwITJFtw.PeWKbLo1bfdfdPhVFASKM/i3F/dbH98uH7C
searchguard.cookie.password: searchguard_cookie_default_password
```
Has anyone having this error? Please advise me and thanks in advance.

**Comment by ahr12** [comment]
@lyeesim988 I am also facing the same problem. how did you solve this issue? Can you share the solution?
Thanks in advance

**Comment by lyeesim988** [comment]
> @lyeesim988 I am also facing the same problem. how did you solve this issue? Can you share the solution?
> Thanks in advance

@ahr12 I manage to get rid of the error by adding in the neccessary own home configuration in my kibana.yml. I believe you have not yet include it in your yml. Check all your own home setting.

own_home.ssl.certificate:  <-- if your are using REST certificate for http
own_home.ssl.key:  <-- if you have private key for REST certificate

example:
own_home.ssl.certificate: "/etc/elasticsearch/mynode.pem"
own_home.ssl.key: "/etc/elasticsearch/mynode_http.key"

Remember to reinitialize the new setting by restarting your kibana service.

**Comment by ahr12** [comment]
@lyeesim988 Thanks.

**Comment by Yullin** [comment]
@lyeesim988 could i see your https://localhost:19200 config ?
and my "elasticsearch.ssl.verificationMode" is none
but still get this error 
```
{"type":"error","@timestamp":"2019-04-19T12:49:14Z","tags":["fatal","root"],"pid":11891,"level":"fatal","error":{"message":"path must be a string or Buffer","name":"TypeError","stack":"TypeError: path must be a string or Buffer\n    
at Object.fs.openSync (fs.js:646:18)\n    at fs.readFileSync (fs.js:551:33)\n    
at module.exports (/usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:33:14)\n    
at Plugin.init [as externalInit] (/usr/share/kibana/plugins/own_home/index.js:91:9)\n    
at asyncRegister (/usr/share/kibana/src/server/plugins/lib/plugin.js:72:20)\n    
at Object.register (/usr/share/kibana/src/server/plugins/lib/plugin.js:77:7)\n    
at Object.target [as register] (/usr/share/kibana/node_modules/hapi/node_modules/joi/lib/object.js:77:34)\n    
at each (/usr/share/kibana/node_modules/hapi/lib/plugin.js:317:14)\n    
at iterate (/usr/share/kibana/node_modules/items/lib/index.js:36:13)\n    
at Object.exports.serial (/usr/share/kibana/node_modules/items/lib/index.js:39:9)\n    
at module.exports.internals.Server.internals.Plugin.register (/usr/share/kibana/node_modules/hapi/lib/plugin.js:320:11)\n    
at Promise (/usr/share/kibana/node_modules/hapi/lib/promises.js:24:16)\n    
at new Promise (<anonymous>)\n    
at Object.exports.wrap (/usr/share/kibana/node_modules/hapi/lib/promises.js:13:12)\n    
at module.exports.internals.Server.internals.Plugin.register (/usr/share/kibana/node_modules/hapi/lib/plugin.js:164:25)\n    
at Plugin.init (/usr/share/kibana/src/server/plugins/lib/plugin.js:82:28)\n    
at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7407:25)\n    
at callPluginHook (/usr/share/kibana/src/server/plugins/lib/call_plugin_hook.js:37:25)\n    
at <anonymous>"},
"message":"path must be a string or Buffer"}
```
