### ISSUE TITLE
Error: listen EADDRNOTAVAIL 172.18.0.2:9200

### ISSUE THREAD

**Issue by johnzheng1975** [wtakase/kibana-own-home#122]
I try to integrate kibana with kibana-own-home, but received below error:

```
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:kibana@6.2.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:elasticsearch@6.2.4","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:own_home@6.2.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:console@6.2.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:metrics@6.2.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-10-29T03:22:15Z","tags":["status","plugin:timelion@6.2.4","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | /usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:161
kibana_1         |       throw err;
kibana_1         |       ^
kibana_1         | 
kibana_1         | Error: listen EADDRNOTAVAIL 172.18.0.2:9200
kibana_1         |     at Object.exports._errnoException (util.js:1020:11)
kibana_1         |     at exports._exceptionWithHostPort (util.js:1043:20)
kibana_1         |     at Server._listen2 (net.js:1264:19)
kibana_1         |     at listen (net.js:1313:10)
kibana_1         |     at net.js:1423:9
kibana_1         |     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
kibana_1         |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
efk_kibana_1 exited with code 1
```

**Comment by johnzheng1975** [comment]
Code Structure
```
   docker-compose.yaml
   fluentd
       conf
           fluent.conf
       Dockerfile
   kibana
       conf
           kibana.yml
       Dockerfile 
```



[docker-compose.zip](https://github.com/wtakase/kibana-own-home/files/2523692/docker-compose.zip)

**Comment by shiveshabhishek** [comment]
@johnzheng1975 , are you trying to configure the same in docker ?

**Comment by johnzheng1975** [comment]
@shiveshabhishek   yes, I want to try with docker-compose.yaml firstly, then try it in kubernetes

**Comment by johnzheng1975** [comment]
@doctor-q , set env variable "ELASTICSEARCH_URL" in kibana container?
I already added  links:
      - "elasticsearch",
And, the hostname port of es in exception string "Error: listen EADDRNOTAVAIL 172.18.0.2:9200" is correct. I can "curl 172.18.0.2:9200" in other container of docker-compose.

**Comment by doctor-q** [comment]
@johnzheng1975  No, I means don't do that. The env variable "ELASTICSEARCH_URL" will  overwrite the config "elasticsearch.url" in kibana.yml .

**Comment by shiveshabhishek** [comment]
@johnzheng1975 , I don't know exactly for docker-compose.yaml, but for running directly the kibana container, I did `docker run --name some-kibana -e ELASTICSEARCH_URL=http://172.18.0.2:9200 -p 5601:5601 -d kibana`
and it worked
and if it doesn't try 
`docker run --name some-kibana -e ELASTICSEARCH_URL=http://0.0.0.0:9200 -p 5601:5601 -d kibana`
convert this in docker-compose.yaml way and try once. Hopefully, it will work.
