### ISSUE TITLE
[Bug] kibana crashes when using wildcards in dev tools

### ISSUE THREAD

**Issue by Sawadski** [wtakase/kibana-own-home#17]
In `Kibana / Dev Tools` when using wildcard queries with empty results, the own home plugin crashes.

## Reproduce this bug

For example, use indices `GET _cat/indices`
```
yellow open a-2017.03.27		xxxxxxxxxxxxxxxxxxxxxx 5 1  14 0 1.3kb 1.3kb
yellow open b-2017.03.27		xxxxxxxxxxxxxxxxxxxxxx 5 1  16 0 1.4kb 1.4kb
yellow open .kibana		        xxxxxxxxxxxxxxxxxxxxxx 1 1   2 0 8.2kb 8.2kb
```

When using the curl command `curl -XGET localhost:9200/_cat/indices/a-2017.02.*` you will get an empty result.

But on `Kibana / Dev Tools` by using `GET _cat/indices/a-2017.02.*` kibana crashes with following log messages:

```
/kibana/plugins/own_home/server/proxy/init_proxy.js:124
            if (replacedIndex && payload[replacedIndex]) {
                                        ^

TypeError: Cannot read property '.kibana_admin' of null
    at /kibana/plugins/own_home/server/proxy/init_proxy.js:88:41
    at finish (/kibana/node_modules/wreck/lib/index.js:301:20)
    at wrapped (/kibana/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/kibana/node_modules/wreck/lib/index.js:356:16)
    at g (events.js:291:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:514:14)
    at endWritable (_stream_writable.js:524:3)
    at Writable.end (_stream_writable.js:489:5)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Waiting for the debugger to disconnect...
```

## Possible Solution (Workaround)

In order to avoid this kind of erroneous behaviour, there is a work around:

In file `kibana/plugins/own_home/server/proxy/init_proxy.js`, change [line 88](https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L88) to 

```
if (replacedIndex && payload && payload[replacedIndex]) {
```

and change [line 92](https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L92) to

```
if (replacedIndex && payload && payload['error']) {
```

This works for my use case, however I am not sure if this solution will introduce new side effects.

**Comment by wtakase** [comment]
Thanks for the report.
I fix it.
https://github.com/wtakase/kibana-own-home/blob/master/server/proxy/init_proxy.js#L87-L107
