### ISSUE TITLE
Own Home with Docker-Elk and Search Guard

### ISSUE THREAD

**Issue by Sawadski** [wtakase/kibana-own-home#44]
In the README, I found information regarding the setup of [own home and search guard](https://github.com/wtakase/kibana-own-home#extract-username-from-session-instead-of-request-header-experimental). Furthermore, I run the Elastic Stack with docker. A good example for integrating the Elastic Stack and Docker is outlined in the [docker-elk repository](https://github.com/deviantony/docker-elk). This repository provides also a branch dedicated to [integration of search-guard](https://github.com/deviantony/docker-elk/tree/searchguard). My aim is to run the docker-elk repo with searchguard together with own home. However, I fail to set up the three components together. This is what I did so far:

1) Checkout the commit hash [6038734](https://github.com/deviantony/docker-elk/commit/603873442c05ce525e51708670db5acde0acd83c) of docker-elk repository  (because I am currently using the elastic stack version 5.3.0)

2) Adapt the Kibana Dockerfile by adding own-home installation via RUN statement:

```
# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.3.0
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.3.0-1/searchguard-kibana-5.3.0-1.zip
RUN kibana-plugin install https://github.com/wtakase/kibana-own-home/releases/download/v5.3.0-2/own_home-5.3.0-2.zip
```

3) Adapt the Kibana configuration (kibana.yml):

```
---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
server.defaultRoute: /app/own_home
# elasticsearch.url: http://localhost:19200
elasticsearch.url: http://kibana:19200
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
# elasticsearch.username: kibanaserver
# elasticsearch.password: kibanaserver
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
# elasticsearch.ssl.verify: false
elasticsearch.ssl.verificationMode: none
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
# own_home.elasticsearch.url: http://localhost:9200
own_home.elasticsearch.url: http://elasticsearch:9200
# own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.session.secretkey: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
searchguard.cookie.secure: false
# searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
```

As mentioned earlier my current setup is not working. I assume that is due to this misconfigured kibana.yml. In any case, what I did is to copy the suggested own-home configuration for searchguard into the kibana.yml. Then, I applied the following changes:

- Replace localhost with kibana (docker-compose service name) in elasticsearch.url and replace localhost with elasticsearch in own_home.elasticsearch.url
- Adapt searchguard cookie password also for own_home.session.secretkey (Is this a sensible configuration? Do they have to be identical?)
- Change elasticsearch.username and elasticsearch.password to string type.
- The option es.ssl.verify is deprecated. Thus, I changed it to elasticsearch.ssl.verificationMode: none.

4) Then I run: docker-compose up -d

5) When docker is running, execute the searchguard init script by:
docker-compose exec elasticsearch bin/init_sg.sh

6) When I attempt to login with admin:admin, the kibana logs show this internal server error (docker-compose logs kibana):

```
kibana_1         | {“type”:“error”,“@timestamp”:“2017-06-19T09:58:56Z”,“tags”:[],“pid”:7,“level”:“error”,“message”:“Internal Server Error”,“error”:{“message”:“Internal Server Error”,“name”:“Error”,“stack”:“Error: Internal Server Error\n    at async$ (/usr/share/kibana/plugins/searchguard/lib/routes/routes.js:66:43)\n    at tryCatch (/usr/share/kibana/node_modules/regenerator/runtime.js:61:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/share/kibana/node_modules/regenerator/runtime.js:328:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/regenerator/runtime.js:94:21)\n    at GeneratorFunctionPrototype.invoke (/usr/share/kibana/node_modules/regenerator/runtime.js:136:37)\n    at bound (domain.js:280:14)\n    at GeneratorFunctionPrototype.runBound (domain.js:293:12)“},“url”:{“protocol”:null,“slashes”:null,“auth”:null,“host”:null,“port”:null,“hostname”:null,“hash”:null,“search”:“”,“query”:{},“pathname”:“/searchguard/api/v1/auth/login”,“path”:“/searchguard/api/v1/auth/login”,“href”:“/searchguard/api/v1/auth/login”}}
kibana_1         | Debug: internal, implementation, error
kibana_1         |     Error: Internal Server Error
kibana_1         |     at async$ (/usr/share/kibana/plugins/searchguard/lib/routes/routes.js:66:43)
kibana_1         |     at tryCatch (/usr/share/kibana/node_modules/regenerator/runtime.js:61:40)
kibana_1         |     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/share/kibana/node_modules/regenerator/runtime.js:328:22)
kibana_1         |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/regenerator/runtime.js:94:21)
kibana_1         |     at GeneratorFunctionPrototype.invoke (/usr/share/kibana/node_modules/regenerator/runtime.js:136:37)
kibana_1         |     at bound (domain.js:280:14)
kibana_1         |     at GeneratorFunctionPrototype.runBound (domain.js:293:12)
```

If you have any suggestion especially on the kibana.yml or this setup in general I would highly appreciate it. Thank you very much in advance.
Add Comment

**Comment by wtakase** [comment]
What about [this patch](https://github.com/floragunncom/search-guard-kibana-plugin/pull/21/files)?

**Comment by Sawadski** [comment]
Thanks for the quick reply. I updated the kibana plugin from version 5.3.0-1 to version 5.3.0-2. 
After attempting to login with admin:admin I get this error message:

```
kibana_1         | {"type":"log","@timestamp":"2017-06-19T12:31:08Z","tags":["error","elasticsearch","data"],"pid":6,"message":"Request error, retrying\nGET http://kibana:19200/_xpack => socket hang up"}
kibana_1         | {"type":"error","@timestamp":"2017-06-19T12:30:39Z","tags":[],"pid":6,"level":"error","message":"Request Timeout after 30000ms","error":{"message":"Request Timeout after 30000ms","name":"Error","stack":"Error: Request Timeout after 30000ms\n    at async$ (/usr/share/kibana/plugins/searchguard/lib/auth/routes.js:84:43)\n    at tryCatch (/usr/share/kibana/node_modules/regenerator/runtime.js:61:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/share/kibana/node_modules/regenerator/runtime.js:328:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/regenerator/runtime.js:94:21)\n    at GeneratorFunctionPrototype.invoke (/usr/share/kibana/node_modules/regenerator/runtime.js:136:37)\n    at bound (domain.js:280:14)\n    at GeneratorFunctionPrototype.runBound (domain.js:293:12)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/searchguard/api/v1/auth/login","path":"/searchguard/api/v1/auth/login","href":"/searchguard/api/v1/auth/login"}}
kibana_1         | Debug: internal, implementation, error
kibana_1         |     Error: Request Timeout after 30000ms
kibana_1         |     at async$ (/usr/share/kibana/plugins/searchguard/lib/auth/routes.js:84:43)
kibana_1         |     at tryCatch (/usr/share/kibana/node_modules/regenerator/runtime.js:61:40)
kibana_1         |     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/share/kibana/node_modules/regenerator/runtime.js:328:22)
kibana_1         |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/regenerator/runtime.js:94:21)
kibana_1         |     at GeneratorFunctionPrototype.invoke (/usr/share/kibana/node_modules/regenerator/runtime.js:136:37)
kibana_1         |     at bound (domain.js:280:14)
kibana_1         |     at GeneratorFunctionPrototype.runBound (domain.js:293:12)
```

**Comment by Sawadski** [comment]
Thanks for the hint, now it works. 
I actually checked out the wrong version.
