### ISSUE TITLE
ES 5.5.0 support

### ISSUE THREAD

**Issue by hijakk** [wtakase/kibana-own-home#50]
When I check out the project from git, update package.json to 5.5.0 and do an npm build, everything seems successful. When I try to start Kibana, I get the following error log:
```
$ ./bin/kibana
  log   [16:28:54.461] [fatal] Error: Cannot find module '../../../../src/core_plugins/elasticsearch/lib/kibana_index_mappings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/plugins/kibana-own-home/server/proxy/create_kibana_index.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/plugins/kibana-own-home/server/proxy/replace_kibana_index_in_path.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:144:5)
FATAL { Error: Cannot find module '../../../../src/core_plugins/elasticsearch/lib/kibana_index_mappings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/plugins/kibana-own-home/server/proxy/create_kibana_index.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/plugins/kibana-own-home/server/proxy/replace_kibana_index_in_path.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/hijakk/Downloads/kibana-5.5.0-darwin-x86_64/node_modules/babel-register/lib/node.js:144:5) code: 'MODULE_NOT_FOUND' }
```

**Comment by wtakase** [comment]
Hi, [v5.5.0](https://github.com/wtakase/kibana-own-home/tree/v5.5.0) is released.

**Comment by hijakk** [comment]
Confirming I got this installed and working, thanks @wtakase
