### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by splasencia** [wtakase/kibana-own-home#56]
Hi,

I'm not being able to setup own_home with x-pack because I get an error complaining about the certificates but the certificates are OK.

I've the following setup:
Apache 2.4
Elastic 5.6.2
Kibana 5.6.2
X-Pack 5.6.2
Own-Home 5.6.2

This is the kibana.yml configuration:

elasticsearch.username: elastic
elasticsearch.password: changeme
elasticsearch.preserveHost: true
elasticsearch.url: "https://ownhome:19200"
kibana.defaultAppId: discover
kibana.index: ".kibana"
logging.dest: /var/log/kibana/kibana.log
logging.verbose: false
server.host: "localhost"
server.name: "Kibana OwnHome Test"
server.port: 5601
server.defaultRoute: /app/own_home
elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.certificateAuthorities: /etc/kibana/x-pack/ca.crt
server.ssl.certificate: /etc/kibana/x-pack/kibana.crt
server.ssl.key: /etc/kibana/x-pack/kibana.key
server.ssl.enabled: true
xpack.security.enabled: true
elasticsearch.requestHeadersWhitelist: [ es-security-runas-user, authorization, cookie ]
own_home.proxy_user_header: es-security-runas-user
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.ssl.certificate: '/etc/kibana/x-pack/ownhome.crt'
own_home.ssl.key: '/etc/kibana/x-pack/ownhome.key'
own_home.elasticsearch.url: https://elasticsearch:9200
own_home.elasticsearch.ssl.certificateAuthorities: '/etc/kibana/x-pack/ca.crt'
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: true
own_home.session.timeout: 3600000
own_home.local.enabled: true
own_home.local.groups: [ public ]

Apache authenticates the user successfully and sends the 'es-security-runas-user' header. I can access Kibana but all searchs return empty results. When I try to access Own Home I get an empty page (just the Kibana menu at the left).

I see the following error at the kibana log file:

{"type":"error","@timestamp":"2017-10-25T14:08:12Z","tags":[],"pid":727,"level":"error","message":"Uncaught error: unable to verify the first certificate","e
rror":{"message":"Uncaught error: unable to verify the first certificate","name":"Error","stack":"Error: Uncaught error: unable to verify the first certifica
te\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n
   at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"url":{
"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/api/own_home/selection","p
ath":"/api/own_home/selection","href":"/api/own_home/selection"}}

I've verified the certificates with:

openssl s_client -CAfile /etc/kibana/x-pack/ca.crt -connect ownhome:19200
Result:       Verify return code: 0 (ok)
curl --cacert /etc/kibana/x-pack/ca.crt -u elastic:changeme -XGET 'https://ownhome:19200/blog/post/1'
Result:       I've got the expected entry
openssl s_client -CAfile /etc/kibana/x-pack/ca.crt -connect ownhome:19200
Result:       Verify return code: 0 (ok)
curl --cacert /etc/kibana/x-pack/ca.crt -u elastic:changeme -XGET 'https://elasticsearch:19200/blog/post/1'
Result:       I've got the expected entry

So both curl and openssl are able to verify the certificates using the CA file. The certificates are thus OK but Kibana complains about not being able to verify them. The following parameters should ensure that the certificates are validated against the proper CA:
own_home.elasticsearch.ssl.certificateAuthorities: '/etc/kibana/x-pack/ca.crt'
elasticsearch.ssl.certificateAuthorities: /etc/kibana/x-pack/ca.crt

As this is the first time I'm trying to set up OwnHome I don't know whether this is a bug or I'm doing something wrong.

In case you need more info, please let me know.

Thanks in advance!

**Comment by splasencia** [comment]
Looks like it was a permission issue. After installing the plugin with: bin/kibana-plugin install file:///tmp/own_home-5.6.2.zip some files in the folder are owned by root. Changing permissions to kibana:kibana then it works.

However, I still don't know why a permission issue in the folder makes Kibana complain about the certificate.

**Comment by splasencia** [comment]
I've verified the default permissions of the folder '/usr/share/kibana/plugins/own_home' and some files were owned by root after default installation of the plugin with the following command in debian:
bin/kibana-plugin install file:///tmp/own_home-5.6.2.zip

I've changed the permissions to kibana:kibana and now it does not complain about the certificate and it works ok.

So, it seems to be an issue with the plugin installation but it is weird that a file permission issue make Kibana complains about the certificate.
