### ISSUE TITLE
Kibana wont start after installing own-home in docker container. Getting the below error.

### ISSUE THREAD

**Issue by athuljays** [wtakase/kibana-own-home#75]
kibana-multi-dash | /usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:161
kibana-multi-dash |       throw err;
kibana-multi-dash |       ^
kibana-multi-dash |
kibana-multi-dash | Error: listen EADDRNOTAVAIL 192.168.99.100:9200
kibana-multi-dash |     at Object.exports._errnoException (util.js:1020:11)
kibana-multi-dash |     at exports._exceptionWithHostPort (util.js:1043:20)
kibana-multi-dash |     at Server._listen2 (net.js:1249:19)
kibana-multi-dash |     at listen (net.js:1298:10)
kibana-multi-dash |     at net.js:1408:9
kibana-multi-dash |     at _combinedTickCallback (internal/process/next_tick.js:83:11)
kibana-multi-dash |     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by wtakase** [comment]
Without information of your kibana.yml and your docker image, I have no any idea about it.

**Comment by athuljays** [comment]
@wtakase : You can find the details of kibana.yml and docker image in the gist below :

[https://gist.github.com/athuljays/6d7ebeec2cb74e93ac0707f446d01689
](url)

**Comment by dayaftereh** [comment]
Hey, my problem was solved with #68
