### ISSUE TITLE
 Waiting for Kibana index ".kibana_GROUP1" to come online failed.

### ISSUE THREAD

**Issue by gogand11** [wtakase/kibana-own-home#93]
Hello,

I have installed Kibana own-home on my Kibana 6.2.3/ES 6.2.3/X-PACK 6.2.3
In my Kibana.yml i have defined the following groups: GROUP1, GROUP2, ADMIN as follows:

elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.local.groups: [ GROUP1, GROUP2, ADMIN ]

When starting my kibana, i have the three groups: group1, group2, admin. But when i try to go on the group1 space, i have the error on my kibana console:

"Unhandled rejection Error: Waiting for Kibana index ".kibana_GROUP1" to come online failed.
    at callWithInternalUser.catch (.../kibana-6.2.3-windows-x86_64/plugins/kibana-own-home-master/server/proxy/create_kibana_index.js:24:13)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (...\kibana-6.2.3-windows-x86_64\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)"

Why is the Kibana unable to create a new index for the Group1?

Thanks...

**Comment by nikuljain** [comment]
Facing same issue - can anyone help

**Comment by nikuljain** [comment]
@gogand11 Can you create group name without numerical like groupa groupb and try please

**Comment by siminicam** [comment]
According to Elasticsearch documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html)

> Index name limitations

There are several limitations to what you can name your index. The complete list of limitations are:

    Lowercase only
    Cannot include \, /, *, ?, ", <, >, |, ` ` (space character), ,, #
    Indices prior to 7.0 could contain a colon (:), but that’s been deprecated and won’t be supported in 7.0+
    Cannot start with -, _, +
    Cannot be . or ..
    Cannot be longer than 255 bytes (note it is bytes, so multi-byte characters will count towards the 255 limit faster)
