### ISSUE TITLE
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

### ISSUE THREAD

**Issue by camjoex** [wtakase/kibana-own-home#98]
Hello
I'm using kibana version 6.2.3 and  i'm trying to install the own_home plugin as specified in in this guide, like this:

1- Downloading  file  https://github.com/wtakase/kibana-own-home/releases/download/v6.2.4/own_home-6.2.4.zip

2 - Installing like this 

root@3cc946c9f8a6:# /opt/kibana/bin/kibana-plugin install file:///root/own_home-6.2.4.zip
Attempting to transfer from file:///tmp/own_home-6.2.4.zip

But i get this errors 

Transferring 608 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /opt/kibana/node_modules/yauzl/index.js:179:14
    at /opt/kibana/node_modules/yauzl/index.js:539:5
    at /opt/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:683:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

Any idea to help me ?
Thank

**Comment by wtakase** [comment]
Could you check the size of your own_home-6.2.4.zip?
Or try to the following method:
```
$ bin/kibana-plugin install https://github.com/wtakase/kibana-own-home/releases/download/v6.2.4/own_home-6.2.4.zip
Attempting to transfer from https://github.com/wtakase/kibana-own-home/releases/download/v6.2.4/own_home-6.2.4.zip
Transferring 3657906 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```
